include $(__nmk_dir)/utils.mk
include ../scripts/feature-tests.mak

CONFIG := include/config.h

ifeq ($(call try-cc,$(LIBBSD_DEV_TEST),-lbsd),y)
        LIBS	+= -lbsd
        DEFINES	+= -DCONFIG_HAS_LIBBSD
endif

ifeq ($(call pkg-config-check,libselinux),y)
        LIBS	+= -lselinux $(LIBS)
        DEFINES	+= -DCONFIG_HAS_SELINUX
endif

$(CONFIG): include/config-base.h
	$(call msg-gen, $@)
	$(Q) @echo '#ifndef __CR_CONFIG_H__' > $@
	$(Q) @echo '#define __CR_CONFIG_H__' >> $@
	$(Q) @echo '' >> $@
	$(Q) @echo '#include "config-base.h"' >> $@
	$(Q) @echo '' >> $@
ifeq ($(call try-cc,$(TCP_REPAIR_TEST),,$(DEFINES)),y)
	$(Q) @echo '#define CONFIG_HAS_TCP_REPAIR' >> $@
	$(Q) @echo '' >> $@
endif
ifeq ($(call try-cc,$(PRLIMIT_TEST),,$(DEFINES)),y)
	$(Q) @echo '#define CONFIG_HAS_PRLIMIT' >> $@
	$(Q) @echo '' >> $@
endif
ifeq ($(call try-cc,$(STRLCPY_TEST),$(LIBS),$(DEFINES)),y)
	$(Q) @echo '#define CONFIG_HAS_STRLCPY' >> $@
	$(Q) @echo '' >> $@
endif
ifeq ($(call try-cc,$(STRLCAT_TEST),$(LIBS),$(DEFINES)),y)
	$(Q) @echo '#define CONFIG_HAS_STRLCAT' >> $@
	$(Q) @echo '' >> $@
endif
ifeq ($(call try-cc,$(PTRACE_PEEKSIGINFO_TEST),,$(DEFINES)),y)
	$(Q) @echo '#define CONFIG_HAS_PEEKSIGINFO_ARGS' >> $@
	$(Q) @echo '' >> $@
endif
ifeq ($(VDSO),y)
	$(Q) @echo '#define CONFIG_VDSO' >> $@
	$(Q) @echo '' >> $@
endif
ifeq ($(call try-cc,$(SETPROCTITLE_INIT_TEST),-lbsd,$(DEFINES)),y)
	$(Q) @echo '#define CONFIG_HAS_SETPROCTITLE_INIT' >> $@
	$(Q) @echo '' >> $@
endif
ifeq ($(piegen-y),y)
	$(Q) @echo '#define CONFIG_PIEGEN' >> $@
	$(Q) @echo '' >> $@
endif
	$(Q) @echo '#endif /* __CR_CONFIG_H__ */' >> $@

config: $(CONFIG)
PHONY += config
